description:
  - seed 変更しながら複数の実験
  - fold 10
data:
  train: ../output/preprocess/table/make_table_dataset/009/train.csv
  test: ../output/preprocess/table/make_table_dataset/009/test.csv
  tfidf: ../output/preprocess/preprocess_v1/tfidf_en_text.joblib

save_path:
  ../output/table/seed_change_exec_lgbm_train/011/
seed_list:
  - 3407
  - 777
target_transform_types:
#  - None
  - log

num_boost_round: 10000

train_setting:
  fold_num: 10
  es_rounds: 200
  key: is_loan_amount_outlier

lgbm_params:
  objective: regression
  boosting: gbdt
  tree_learner: serial
  learning_rate: 0.01
  bagging_freq: 1
  lambda_l1: 0
  lambda_l2: 1
  num_threads: 4
  metric: mae
  max_depth: -1
  num_leaves: 64
  max_bin: 255
  bagging_fraction: 0.8
  feature_fraction: 0.8
  min_data_in_leaf: 20

remove_features:
  - LOAN_ID
  - DESCRIPTION
  - DESCRIPTION_TRANSLATED
  - LOAN_AMOUNT
  - IMAGE_ID
  - LOAN_USE
  - COUNTRY_NAME
  - CURRENCY_POLICY
  - CURRENCY_EXCHANGE_COVERAGE_RATE
  - TAGS
  - clean_DESCRIPTION_TRANSLATED
  - clean_DESCRIPTION_TRANSLATED_tfidf
  - DISTRIBUTION_MODEL
  - roberta_pred_loan_use

label_enc_features:
  - ORIGINAL_LANGUAGE
  - REPAYMENT_INTERVAL
  - SECTOR_NAME
  - country_code_sector_name
  - LOAN_USE_first_word

target_enc_features:
  - ACTIVITY_NAME
  - COUNTRY_CODE
  - CURRENCY
  - TOWN_NAME
